openapi: 3.0.3
info:
  title: 'performis IF2FI'
  description: 'performis IF2FI | Interface for Financial Accounting'
  contact:
    email: 'support@infosystem.ch'
  license:
    name: 'Proprietary Infosystem AG'
    url: http://www.infosystem.ch
  version: 3.0.0
security:
    - basicAuth: []
paths:
  /v3/AccountReceivable:
    get:
      tags:
      - AccountReceivable
      summary: Searches for AccountReceivables
      description: With this interfaces, the account receivables can be searched
      operationId: searchAccountreceivable
      parameters:
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/x-RequestingSystem'
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/x-RequestingUser'
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/x-Flow-ID'
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/searchString'
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/skip'
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/limit'
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/ChangesSinceDateTime'
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/ChangeSinceChangeID'
      - name: internalBpAddrID
        in: query
        description: |
          Retrieve specific AccountReceivable record by internal business partner id. (Ignores other search options if provided)
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 9999999999
          example: 57812
        #DEV: Übergebene interne performis ID. Andere Suchfelder können ignoriert werden wenn diese ID mitgegeben wird.
      - name: externalBpAddrID
        in: query
        description: |
          Retrieve specific AccountReceivable record by external business partner address ID. (Ignores searchString parameter if provided)
        required: false
        schema:
          type: string
          maxLength: 50
          example: '6f22f981-a9e7-4eba-b3ac-df1b869eb090'
        #DEV: Übergebene externe ID. Suchstring kann ignoriert werden wenn dieser Parameter mitgegeben wird.
      responses:
        200:
          description: Search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountReceivables'
        400:
          $ref: './CommonResponseCodes-3.0.0.yaml#/400' 
        401:
          $ref: './CommonResponseCodes-3.0.0.yaml#/401' 
        403:
          $ref: './CommonResponseCodes-3.0.0.yaml#/403' 
        404:
          $ref: './CommonResponseCodes-3.0.0.yaml#/404' 
    put:
      tags:
      - AccountReceivable
      summary: Update or create an AccountReceivable
      description: Updates or creates an AccountReceivable
      operationId: putAccountReceivable
      parameters:
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/x-RequestingSystem'
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/x-RequestingUser'
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/x-Flow-ID'
      requestBody:
        description: account receivable to update or create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountReceivable'
              #DEV: Schema enthält jeweils interne und externe IDs zu MA, GP-MA und GP-Arbeitsort. Controller soll beide (intern und externe) IDs handeln können. Fremdsystem muss nicht zwingend performis IDs kennen.
        required: false
      responses:
        200:
          description: account receivable updated. returns updated record.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountReceivable'
        201:
          description: account receivable created. returns created record.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountReceivable'
        400:
          $ref: './CommonResponseCodes-3.0.0.yaml#/400' 
        401:
          $ref: './CommonResponseCodes-3.0.0.yaml#/401' 
        403:
          $ref: './CommonResponseCodes-3.0.0.yaml#/403' 
        404:
          $ref: './CommonResponseCodes-3.0.0.yaml#/404' 
  /v3/AccountReceivable/CreditLimit:
    put:
      tags:
      - AccountReceivable
      summary: Updates specified account receivable credit limit
      description: |
        Used to submit the current, open amount on a given account when 
        performis is not the leading accounting system.
      operationId: putCreditLimit
      parameters:
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/x-RequestingSystem'
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/x-RequestingUser'
      - $ref: './CommonRequestHeaders-3.0.0.yaml#/x-Flow-ID'
      requestBody:
        description: account to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditLimit'
              #DEV: Schema enthält jeweils interne und externe IDs zu MA, GP-MA und GP-Arbeitsort. Controller soll beide (intern und externe) IDs handeln können. Fremdsystem muss nicht zwingend performis IDs kennen.
        required: false
      responses:
        200:
          description: accountreceivable updated. returns updated record.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditLimit'
        400:
          $ref: './CommonResponseCodes-3.0.0.yaml#/400' 
        401:
          $ref: './CommonResponseCodes-3.0.0.yaml#/401' 
        403:
          $ref: './CommonResponseCodes-3.0.0.yaml#/403' 
        404:
          $ref: './CommonResponseCodes-3.0.0.yaml#/404' 
  
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  
  schemas:
    CreditLimit:
      required:
      - CompanyNo
      - AccountNo
      - CreditLimit
      type: object
      properties:
        CompanyNo:
          type: integer
          minimum: 0
          maximum: 999999
          description: 'Company of the account receivable'
          example: 11
        AccountNo:
          type: integer
          minimum: 1
          maximum: 9999999999
          description: 'The account number of the account receivable. Note that the account number must remain unique within a company.'
          example: 28500
        CreditLimit:
          type: integer
          minimum: 0
          maximum: 999999999999999999
          nullable: true
          description: 'Maximum amount of open items this subledger account is allowed to have. An empty credit limit allows unrestricted open items'
          example: 23500

    AccountReceivables:
      type: object
      properties:
        Partners:
          type: array
          items:
            $ref: '#/components/schemas/AccountReceivable'
    
    AccountReceivable:
      required:
      - Active
      - Accounts
      type: object
      properties:
        ChangeID:
          type: integer
          minimum: 1
          maximum: 9999999999
          description: 'ChangeID of the entity.'
          example: 4711
        ChangeDate:
          type: string
          format: datetime
          description: 'ChangeDate of the entity.'
        BpAddrID:
          type: integer
          minimum: 1
          maximum: 9999999999
          description: 'performis Address ID - This ID uniquely identifies an address in performis. For example, ID "629" for address "Infosystem AG, Wil". To identify the address, either the performis address ID (BpAddrID) or the ID of the external system (ExternalBpAddrID) is required.'
          example: 281902
        ExternalBpAddrID:
          type: string
          maxLength: 50
          description: 'Third-party address ID - This ID must be unique within the origin (Origin field). As ID it is recommended to use either the Primary Key of the foreign system or a GUID (Global Unique Identifier). For example, ID "629c5d97-a225-4b08-877c-e8a802c23014" for origin "ERP".		To identify the address, either the performis address ID (BpAddrID) or the ID of the external system (ExternalBpAddrID) is required.'
          example: 'f3f6f4bb-61d0-4507-9bfc-e3134c4ea9a5'
        Origin:
          type: string
          maxLength: 10
          description: 'Origin of the business partner, name of the third-party system. Business partners and addresses with an origin can''t be edited in performis.'
          example: 'SAP'
        Active:
          type: boolean
          description: 'Defines whether or not the subledger account head is active or not.'
          example: true
        VATRegistryNo:
          type: string
          maxLength: 20
          nullable: true
          description: 'VAT Registry No - UID'
          example: 'CHE-123.456.789'
        VATIdentityNo:
          type: string
          maxLength: 20
          nullable: true
          description: 'VAT Identity No'
          example: 'CHE-107.823.285 MWST'
        TaxOffice:
          type: string
          maxLength: 60
          nullable: true
          description: 'Name of dedicated tax office'
          example: 'St. Gallen'
        LastCreditReport:
          type: string
          format: date
          nullable: true
          description: 'Date of last Credit Report'
          example: '2021-07-21'
        Annotation:
          type: string
          maxLength: 1000
          nullable: true
          description: 'Any annotations in regard to this accountreceivable'
          example: 'Account in use since 2013.'
        Accounts:
          type: array
          items:
            $ref: '#/components/schemas/Account'

    Account:
      required:
      - Active
      - Currency
      - AuthorisationGroup
      - SummaryAccount
      - PaymentTerms
      type: object
      properties:
        AccountNo:
          type: integer
          minimum: 1
          maximum: 9999999999
          description: 'The account number of the account receivable. Note that the account number must remain unique within a company. If no account number is submitted, performis will generate an account number. ATTENTION, the account can only be updated with this number, so it should always be transferred.'
          example: 28500
        Active:
          type: boolean
          description: 'Defines whether or not the account is active and therefore useable.'
          example: true
        Currency:
          type: string
          maxLength: 3
          description: 'Currency (ISO 4217)'
          example: 'CHF'
          #DEV: convert from c26 to ISO code on FID 93
        AuthorisationGroup:
          type: integer
          minimum: 1
          maximum: 99999999
          nullable: true
          description: 'The authorization group to which this subledger account is assigned. c212 account receivable/c213 account payable'
          example: 39810
        SummaryAccount:
          type: integer
          minimum: 1
          maximum: 9999999999
          description: 'General ledger summay account for this subledger account.'
          example: 28000
        PaymentTerms:
          type: integer
          minimum: 1
          maximum: 9999999999
          description: 'Default Payment Terms of this subledger account, refer to value list supplied by infosystem. c27'
          example: 5
        VATCodeDefault:
          type: integer
          minimum: 1
          maximum: 99999999
          description: 'Default VAT Code. c23'
          example: 40900
        VATIncl:
          type: boolean
          description: 'VAT Incl. default setting'
          example: false
        VATNoDefault:
          type: boolean
          description: 'Defines whether or not a default VAT code is loaded from general ledger account'
          example: false
        CreditLimit:
          type: integer
          minimum: 0
          maximum: 999999999999999999
          nullable: true
          description: 'Maximum amount of open items this subledger account is allowed to have. An empty credit limit allows unrestricted open items.'
          example: 23500
        DelCredere:
          type: integer
          minimum: 0
          maximum: 999
          nullable: true
          description: 'Del credere risk in percent'
          example: 0
        AutomatedOISettlement:
          type: boolean
          description: 'Automated open item settlement'
          example: false
        DiscountPeriodTolerance:
          type: integer
          minimum: 0
          maximum: 99
          nullable: true
          description: 'Discount tolerance in days'
          example: 3
        MaxWriteOffInPercent:
          type: integer
          minimum: 0
          maximum: 99
          nullable: true
          description: 'Maximum write off in percentage'
        MaxWriteOffInCurrency:
          type: integer
          minimum: 0
          maximum: 99999999.99
          nullable: true
          description: 'Maximum write off in amount'
          example: 100.00
        DebitDirect:
          type: boolean
          nullable: true
          description: 'Defines if the account payable uses debit direct for payment.'
          example: true   
        DebitDirectRescission:
          type: boolean
          nullable: true
          description: 'If the account receivable uses debit direct, he may be able to use a rescission if selected.'
          example: true
        PaymentAccount:
          type: integer
          minimum: 0
          maximum: 9999999999
          nullable: true
          description: 'Payment account, if not provided the company default will be used.'
          example: 44200
        InterestType:
          type: string
          maxLength: 10
          nullable: true
          description: 'Type of interest which is used for subledger' 
          example: ''
        PaymentMethod:
          type: integer
          minimum: 1
          maximum: 99999999
          nullable: true
          description: 'Payment Method. c913' 
          example: null
        PaymentGroup:
          type: integer
          minimum: 1
          maximum: 99999999
          nullable: true
          description: 'Payment Group. c214' 
          example: null
        FeeAgreement:
          type: integer
          minimum: 1
          maximum: 99999999
          nullable: true
          description: >
            DTA rules for charges:
              * customer
              * Beneficiary
              * Splitting
          example: null
        BankingConnectionId:
          type: integer
          minimum: 1
          maximum: 9999999999
          nullable: true
          description: 'Default banking connection used by the account receivable for payments' 
          example: null
        DunningKeys:
          type: array
          items:
            $ref: '#/components/schemas/DunningKey'

    DunningKey:
      required:
      - DunningRating
      type: object
      description: |
        With the dunning keys, the open items of the account receivable can be split into different groups.
      properties:
        ReminderKey:
          type: string
          maxLength: 50
          description: 'Dunning key name'
          nullable: true
          example: null
        Description:
          type: string
          maxLength: 60
          description: 'User defined description of dunning key'
          example: null
        DunningRating:
          type: integer
          minimum: 0
          maximum: 99999999
          nullable: true
          description: 'Account Receivable dunning rating. c213'
          example: 82999
        DunningAddressBpAddrID:
          type: integer
          minimum: 1
          maximum: 9999999999
          description: 'performis Address ID of the dunning address - This ID uniquely identifies an address in performis. For example, ID "629" for address "Infosystem AG, Wil". To identify the address, either the performis address ID (BpAddrID) or the ID of the external system (ExternalBpAddrID) is required.'
          example: 281902
        DunningAddressExternalBpAddrID:
          type: string
          maxLength: 50
          description: 'Third-party address ID of the dunning address - This ID must be unique within the origin (Origin field). As ID it is recommended to use either the Primary Key of the foreign system or a GUID (Global Unique Identifier). Attention, if External IDs are used, no performis IDs may be used in parallel, additionally the Origin field is mandatory. E.g. ID "629c5d97-a225-4b08-877c-e8a802c23014" for origin "SAP". To identify the business partner, either the performis business partner ID (BpID) or the ID of the external system (ExternalBpID) is required.'
          example: 'f3f6f4bb-61d0-4507-9bfc-e3134c4ea9a5'
        DunningBlockCode:
          type: integer
          minimum: 1
          maximum: 99999999
          nullable: true
          description: 'Dunning block code. c204'
          example: 83999
        DunningBlockedUntil:
          type: string
          format: date
          description: 'No dunning until this date'
          example: '2021-07-21'
        DunningGroup:
          type: integer
          minimum: 1
          maximum: 9999999999
          nullable: true
          description: 'Dunning Group of Account Receivable'
          example: 10